config/routes.rb
Rails.application.routes.draw do

  root :to => "surveys#index"
  
  
  resources :surveys
  match "questions/show", :to => "questions#index", :via => :get
  
  resources :questions do
    collection do
      put :quiz_guess
      get :edit_multiple
      put :update_multiple
    end
  end
  

  resources :answers
  
  match ':controller(/:action(/:id))', :via => [:get, :post, :patch, :delete]

  

end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :survey, inverse_of: :questions
	has_many :answers, :dependent => :destroy
	has_many :correct_answers, :dependent => :destroy
	accepts_nested_attributes_for :answers, :correct_answers, :reject_if => lambda { |a| a[:content].blank? }

	scope :sorted, lambda { order("questions.created_at ASC")}

	def points
		self.answers.count
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  #before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :find_survey
  
  def index
    #@questions = Question.where(:survey_id => @survey.id)
    @question = Question.first
    @questions = Question.all
    @surveys = Survey.all
    @survey = Survey.first
  end

  def show
    @answer = Survey.find(params[:id]) #answer
    @answers = Answer.where(:survey_id => @survey.id)
    @question = Survey.find(params[:id])
    @questions = Question.where(:survey_id => @survey.id)
    @surveys = Survey.all
    @survey = Survey.find(params[:id])
  end

  def new
    @questions = Question.all
    @question = Question.new(:survey_id => @survey.id)
    1.times do
      question = @survey.questions.build
      4.times { question.answers.build }
    end
  end

  # POST /surveys
  # POST /surveys.json
  def create
      @question = Question.new(question_params)
      @survey = Survey.find(params[:id])
      @surveys = Survey.all
      @questions = Question.all
      if @question.save
        flash[:notice] = 'Question was successfully created.' 
        redirect_to(:controller => 'surveys', :action => 'index', :survey_id => @survey.id)
      else
        
        render('new') 
      end
  end

  # GET /surveys/1/edit
  def edit
    @question = Question.find(params[:id])
    @surveys = Survey.all
    @page_count = Page.count
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(question_params)
      flash[:notice] = "Question updated successfully."
      redirect_to(:action => 'show', :id => @question.id, :survey_id => @survey.id)
    else
      @surveys = Survey.all
      @page_count = Page.count
      render('edit')
    end
  end 

  def check
    
  end

  def delete
    @question = Question.find(params[:id])
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @question = Question.find(params[:id]).destroy
    flash[:notice] = "Question destroyed successfully."
    redirect_to(:action => 'index', :survey_id => @survey.id)
  end

  def edit_multiple
    @answers = Answer.find(params[:guess_id])
  end

  def quiz_guess
    @survey = Survey.first
    Answer.update(params[:answers].keys, params[:answers].values)
    flash[:notice] = "Guess saved successfully."
    redirect_to(:action => 'show', :id => @survey.next, :survey_id => @survey.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(questions_attributes: [:survey_id, :id, :content, answers_attributes: [:id, :question_id, :correct_answer, :content], correct_answers_attributes: [:guess, :question_id]])
    end

    def find_survey
      # If in each action calling this method (find_survey) has :survey_id sent
      if params[:survey_id]
        # We will then go to the database and look for (and find) :survey_id and set that to @survey. 
        @survey = Survey.find(params[:survey_id])
      end
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer_fields.html.erb
<div class="col-md-10">
  <%= f.text_field :content, :class => 'control-label col-md-6' %>
  <%= f.check_box(:correct_answer) %>
</div>

app/views/questions/_answerii_fields.html.erb
<div class="col-md-10">
  <%= f.text_field :content, :class => 'control-label col-md-6' %>
  <%= f.check_box(:guess) %>
</div>

app/views/questions/_form.html.erb
<%= form_for @survey, :html => { :class => 'form-horizontal' } do |f| %>

      <legend>Question</legend>
        <div class="form-group">
          
            <div class="col-md-offset-2 col-md-10">
                <%= f.fields_for :questions do |ff| %>
                  <%= render 'question_fields', :f => ff %>
                    <%= ff.fields_for :answers do |fff| %>
                        <%= render 'answer_fields', :f => fff %>
                    <% end %>
                <% end %>
            </div>
        </div> 
        <div class="form-group">
          <div class='col-md-offset-1 col-md-10'>
            <%= link_to t('.back', :default => t("helpers.links.surveys")),
                    surveys_path, :class => 'btn btn-default'  %>
            <%= f.submit nil, :class => 'btn btn-primary' %>
            <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                        surveys_path, :class => 'btn btn-default' %>
          </div>
        </div>
<% end %>

app/views/questions/_question_fields.html.erb
<div class="form-group">
  <%= f.text_field :content, :class => 'control-label col-md-6' %><br/><br/>
</div>

app/views/questions/delete.html.erb
<h2>Delete question</h2>

<div class = "question_delete">

  <%= form_for(:question, :url => {:action => 'destroy', :id => @question.id, :survey_id => @survey.id}) do |f| %>

    <p>Are you sure you permanently want to delete the question?</p>
    
    <div class="form_buttons">
      <%= submit_tag("Delete question") %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<td><%= link_to('<< Back to list', {:action => 'index', :survey_id => @survey.id}, :class => 'back-link') %></td>

<h2>Edit question:</h2>

<div class = "question_edit">

  <%= form_for(:question, :url => {:action => 'update', :id => @question.id, :survey_id => @survey.id }) do |f| %>

      <table summary="Question_form_fields">
        <tr>
          <th>Survey ID</th>
          <td><%= f.text_field(:survey_id)%></td>
        </tr>
        <tr>
          <th>Content</th>
          <td><%= f.text_area(:content)%></td>
        </tr>
      </table>
    <div class="form_buttons">
      <%= submit_tag("Update survey") %>
    </div>
  <% end %>
</div>

app/views/questions/edit_multiple.html.erb
<h1>Edit Checked Questions</h1>

<%= form_tag update_multiple_questions_path, method: :put do %>
	<% @answers.each do |answer| %>
	  <h2><%= answer.content %></h2>

		<%= fields_for "answers[]", answer do |f| %>
			<div class="field">
				<%= f.check_box :guess %>
				<%= f.label :guess %>
			</div>
			<div class="actions">
				<%= submit_tag "Update" %>
			</div>
		<% end %>
	<% end %>
<% end %>

app/views/questions/home.html.erb
<h1>Welcome to Quizzes</h1>

<h3>Press start to begin</h3>

<%= link_to t('.start', :default => t("helpers.links.start")),
             question_path(:id => @survey.id, :survey_id => @survey.id), :class => 'btn btn-primary'  %>

app/views/questions/index.html.erb
<h1>Listing Questions</h1>

<table class = "listing" summary = "question_list"> 

    <tr class = "header">
      <th>&nbsp;</th>
      <th>Questions:<br /><br /></th>
      <th>&nbsp;</th>
      <th colspan="3"></th>
    </tr>

    <% @questions.each do |question| %>
      <tr>
        <th>&nbsp;</th>
        <td><%= question.content %></td>
        <th>&nbsp;</th>
        <td class="actions">
      </tr>
    <% end %>
</table>

<br />

  <%= link_to t('.back', :default => t("helpers.links.back")),
              surveys_path, :class => 'btn btn-default'  %>


  

 

app/views/questions/new.html.erb
<td><%= link_to('<< Back to list', {:action => 'index', :survey_id => @survey.id}, :class => 'back-link') %></td>

<div class = "question_new">

  <%= form_for(:question, :url => {:action => 'create', :survey_id => @survey.id}) do |f| %>

      <table summary="Question_form_fields">
        <tr>
          <th>Survey ID</th>
          <td><%= f.text_field(:survey_id) %></td>
        </tr>
        <tr>
          <th>Content</th>
          <td><%= f.text_area(:content) %></td>
        </tr>
      </table>
    <div class="form_buttons">
      <%= submit_tag("Create question") %>
    </div>
  <% end %>
</div>

app/views/questions/new_stray.html.erb
<td><%= link_to('<< Back to list', {:action => 'index'}, :class => 'back-link') %></td>

<div class = "question_new">

  <%= form_for(:question, :url => {:action => 'create'}) do |f| %>

      <table summary="Question_form_fields">
        <tr>
          <td><%= f.label(:survey_id, "Subject") %></td>
          <td><%= f.select(:survey_id, @surveys.map {|s| [s.name, s.id]} ) %></td>
        </tr>
        <tr>
          <th>Content</th>
          <td><%= f.text_area(:content) %></td>
        </tr>
      </table>
    <div class="form_buttons">
      <%= submit_tag("Create question", :class => 'btn btn-primary') %>
    </div>
  <% end %>
</div>

app/views/questions/show.html.erb
<%- model_class = Survey -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<table class="col-md-10">
	<thead>
    <%= form_tag quiz_guess_questions_path, :method => :put do %>
  		<% for question in @survey.questions do %>
  			<li><%= question.content %></li>
  				<% for answer in question.answers do %>
              <li>
                <%= fields_for "answers[]", answer do |f| %>
                  <%= answer.content %>  
                  <%= f.check_box :guess, :checked => false %>    
                <% end %>
              </li>
  				<% end %>
  		<% end %>
     <%= submit_tag "Guess" %>
    <% end %>
	</thead>
</table>


  <%= link_to t('.back', :default => t("helpers.links.back")),
              surveys_path, :survey_id => @survey.id, :class => 'btn btn-default'  %>
  <%= link_to t('Previous question', :default => t("helpers.links.previous")),
              {:action => 'show', :id => @survey.previous, :survey_id => @survey.id}, :class => 'btn btn-default' %>
  <%= link_to t('Next question', :default => t("helpers.links.next")),
             {:action => 'show', :id => @survey.next, :survey_id => @survey.id}, :class => 'btn btn-default' %>

  
  

app/views/questions/show_stray.html.erb
<td><%= link_to('<< Back to list', {:action => 'index', :question_id => @question.id}, :class => 'action_index') %></td>

<div class="question show">
  <h2><strong>Show question:</strong></h2>
	<table summary="Question detail view">
		<tr>
			<th>Survey ID: </th>
				<td><%= @question.survey_id %></td>
		</tr>

		<tr>
			<th>Content: </th>
				<td><%= @question.content %></td>
		</tr>

		<tr>
			<th>Choices: </th>
				<td><%= @question.answers %></td>
		</tr>
	</table>
</div>